##----------------# Spring core configurations #----------------##
spring.application.name=springai.openai
server.port=8081

##----------------# SpringAi OpenAI configurations #----------------##
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4
spring.ai.openai.chat.options.temperature=0.7
